name: NpmTest
run-name: ${{ github.actor }} is creating a basic npm
on: [push, workflow_dispatch]
jobs:
  npm_test:
    runs-on: <github actions runner>
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run test
        run: npm test
